FTP = 60

TOP_OF_SCREEN = (0, 0)

ASTERIX_POSITION = (300, 300)
ASTERIX_SIZE = (200, 200)
ASTERIX_SPEED = 10
ASTERIX_FLIP_X = 1
ASTERIX_FLIP_Y = 0

ROMANS_SPEED = 5
ROMANS_TIME_OUT = 100
ROMANS_MAX_AMOUNT = 5
ROMANS_SIZE = (100, 100)
ROMAIN_HEIGHT_INDENT = 300
ROMAIN_WIGHT_INDENT = 700
ROMAIN_MAX_VECTORS_LENGTH = 100
ROMANS_SMOOTHNESS = 20

WHITE_COLOR = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)

INFINITY_LOOP = -1

PATH_TO_LANDSCAPE = 'images/landscape.png'
PATH_TO_ASTERIX = 'images/asterix.jpg'
PATH_TO_GAME_MUSIC = 'music/game_music.mp3'
PATH_TO_ROMANS = 'images/w-romans.png'
